export type Startup={id:string;name:string;city:string;country:string;lat:number;lng:number;industry:string;stage:string;funding:number;valuation:number|null;founded:number;employees:string;description:string;opportunity:string};
export const startups:Startup[]=[
{id:'zepto',name:'Zepto',city:'Bengaluru',country:'India',lat:12.9716,lng:77.5946,industry:'E-commerce',stage:'Growth',funding:1400,valuation:500, founded:2021,employees:'1,000+',description:'Quick-commerce platform built around dense local fulfillment and rapid delivery.',opportunity:'Shows how logistics infrastructure and consumer frequency can create defensible local networks.'},
{id:'sarvam',name:'Sarvam AI',city:'Bengaluru',country:'India',lat:12.9352,lng:77.6245,industry:'AI',stage:'Series A',funding:41,valuation:180,founded:2023,employees:'100+',description:'Builds AI models and products focused on Indian languages and enterprise use cases.',opportunity:'A strong example of localization as a moat in an emerging AI market.'},
{id:'mistral',name:'Mistral AI',city:'Paris',country:'France',lat:48.8566,lng:2.3522,industry:'AI',stage:'Growth',funding:1000,valuation:6000,founded:2023,employees:'300+',description:'AI company developing foundation models and generative AI products.',opportunity:'Illustrates Europe’s strategy of building frontier AI capabilities outside the largest US labs.'},
{id:'hume',name:'Hume AI',city:'New York',country:'USA',lat:40.7128,lng:-74.006,industry:'AI',stage:'Series B',funding:80,valuation:500,founded:2021,employees:'50+',description:'Develops AI interfaces designed to understand and respond to human emotion and expression.',opportunity:'Human-centered interfaces are an emerging layer between foundation models and applications.'},
{id:'scale',name:'Scale AI',city:'San Francisco',country:'USA',lat:37.7749,lng:-122.4194,industry:'AI',stage:'Growth',funding:600,valuation:25000,founded:2016,employees:'1,000+',description:'Data and AI infrastructure company supporting model development and deployment.',opportunity:'Demonstrates the value of infrastructure businesses built around the AI supply chain.'},
{id:'ramp',name:'Ramp',city:'New York',country:'USA',lat:40.7306,lng:-73.9352,industry:'FinTech',stage:'Growth',funding:1300,valuation:13000,founded:2019,employees:'1,000+',description:'Financial operations platform combining corporate cards, expense management and automation.',opportunity:'Vertical software plus embedded finance can turn a single workflow into a broad platform.'},
{id:'monzo',name:'Monzo',city:'London',country:'UK',lat:51.5072,lng:-0.1276,industry:'FinTech',stage:'Growth',funding:1100,valuation:5000,founded:2015,employees:'3,000+',description:'Digital bank focused on mobile-first consumer financial services.',opportunity:'Consumer trust and product experience can be as important as financial infrastructure.'},
{id:'harness',name:'Harness',city:'San Francisco',country:'USA',lat:37.7849,lng:-122.4094,industry:'SaaS',stage:'Growth',funding:425,valuation:4000,founded:2016,employees:'1,000+',description:'Software delivery platform automating continuous integration, deployment and engineering workflows.',opportunity:'Developer infrastructure remains attractive when it removes measurable engineering friction.'},
{id:'celestia',name:'Celestia',city:'Berlin',country:'Germany',lat:52.52,lng:13.405,industry:'Web3',stage:'Growth',funding:155,valuation:1000,founded:2019,employees:'50+',description:'Modular blockchain network focused on scalable data availability.',opportunity:'Protocol specialization can create new infrastructure layers instead of competing as a general chain.'},
{id:'helsing',name:'Helsing',city:'Munich',country:'Germany',lat:48.1351,lng:11.582,industry:'DefenceTech',stage:'Growth',funding:830,valuation:5000,founded:2021,employees:'500+',description:'Defence technology company developing AI-enabled systems and decision support.',opportunity:'Defence is becoming a major applied-AI market where software can augment existing platforms.'},
{id:'figure',name:'Figure AI',city:'Sunnyvale',country:'USA',lat:37.3688,lng:-122.0363,industry:'Robotics',stage:'Growth',funding:754,valuation:3900,founded:2022,employees:'200+',description:'Develops general-purpose humanoid robots for commercial environments.',opportunity:'Humanoid robotics is a convergence point for AI, perception, manipulation and manufacturing.'},
{id:'retool',name:'Retool',city:'San Francisco',country:'USA',lat:37.784,lng:-122.431,industry:'SaaS',stage:'Growth',funding:140,valuation:3500,founded:2017,employees:'500+',description:'Low-code platform for building internal business applications quickly.',opportunity:'Internal tools remain a large, repetitive software category with strong enterprise willingness to pay.'},
{id:'perplexity',name:'Perplexity',city:'San Francisco',country:'USA',lat:37.78,lng:-122.42,industry:'AI',stage:'Growth',funding:1000,valuation:20000,founded:2022,employees:'200+',description:'AI-powered answer engine combining language models with web search and citations.',opportunity:'Search is being rethought as an answer interface rather than a list of links.'},
{id:'qonto',name:'Qonto',city:'Paris',country:'France',lat:48.866,lng:2.333,industry:'FinTech',stage:'Growth',funding:622,valuation:5000,founded:2016,employees:'1,600+',description:'Business banking and financial management platform for SMEs.',opportunity:'SME financial workflows can be consolidated into software-led banking experiences.'},
{id:'graphcore',name:'Graphcore',city:'Bristol',country:'UK',lat:51.4545,lng:-2.5879,industry:'DeepTech',stage:'Growth',funding:700,valuation:700,founded:2016,employees:'500+',description:'AI semiconductor company developing processors and systems for machine intelligence.',opportunity:'Specialized compute is strategically important as AI workloads reshape semiconductor demand.'},
{id:'agility',name:'Agility Robotics',city:'Corvallis',country:'USA',lat:44.5646,lng:-123.262,industry:'Robotics',stage:'Growth',funding:578,valuation:500,founded:2015,employees:'300+',description:'Builds bipedal robots for logistics and industrial work.',opportunity:'Physical automation targets labor-intensive workflows where reliability can produce clear ROI.'},
{id:'krutrim',name:'Krutrim',city:'Bengaluru',country:'India',lat:12.972,lng:77.61,industry:'AI',stage:'Series B',funding:50,valuation:1200,founded:2023,employees:'200+',description:'Indian AI company developing language models and AI infrastructure.',opportunity:'Localized foundation models can target language, culture and infrastructure constraints.'},
{id:'phonepe',name:'PhonePe',city:'Bengaluru',country:'India',lat:12.9698,lng:77.75,industry:'FinTech',stage:'Growth',funding:2200,valuation:12000,founded:2015,employees:'5,000+',description:'Digital payments and financial services platform serving consumers and businesses.',opportunity:'Payments can become a distribution layer for broader financial products.'}
];
export const industries=['All','AI','FinTech','SaaS','Robotics','DeepTech','DefenceTech','E-commerce','Web3'];
